name: mybio
description: Minha Bio

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  firebase_analytics: ^10.0.5
  
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  url_launcher: ^6.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/